# Generated by Django 5.0.1 on 2024-02-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMSapp', '0004_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
